easy_admin:
    site_name: '<img src="http://www.hbo.com/assets/images/series/game-of-thrones/downloads/wallpaper-iron-throne-1600.jpg" />'
    design:
        brand_color: '#333'
        color_scheme: 'dark'
        form_theme: 'vertical'
    list:
        actions: ['show']