easy_admin:
    entities:
        Model:
            class: PhoneBundle\Entity\Model
            form:
                fields:
                    - name
                    - products
                    - category